### ISSUE TITLE
Exception: Data must be 1-dimensional

### ISSUE THREAD

**Issue by PedroRaposo** [theislab/anndata#152]
Hi, when importing a loom file with scanpy I get the following error.

```
>>> import scanpy.api as sc
>>> adata = sc.read_loom('/path/to/loom_file.loom')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 186, in read_loom
    dtype=dtype)
  File "/opt/conda/lib/python3.7/site-packages/anndata/base.py", line 672, in __init__
    filename=filename, filemode=filemode)
  File "/opt/conda/lib/python3.7/site-packages/anndata/base.py", line 850, in _init_as_actual
    ['obs_names', 'row_names', 'smp_names'])
  File "/opt/conda/lib/python3.7/site-packages/anndata/base.py", line 287, in _gen_dataframe
    columns=[k for k in anno.keys() if k != index_name])
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 56, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 277, in _homogenize
    raise_cast_failure=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 658, in sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional
```

However, I can successfully open the `.loom` file with `loompy`.

```
>>> import loompy
>>> loom_file = loompy.connect("/path/to/loom_file.loom")
>>> loom_file[: , :]
array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 2., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
```

Does someone know why? Thanks you.

**Comment by ivirshup** [comment]
Does this happen with any loom file or just one specifically? 

Would you mind posting a [minimal reproducible example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) we can run? I'm not that familiar with the specifics of loom files and an example that I can run will help me get to this much faster.

**Comment by PedroRaposo** [comment]
Hi @ivirshup, it seems that is happens to every file. Here's an reduced example straight from Seurat itself, and it gives me the same error. Thank you for your time!

[example_seurat.zip](https://github.com/theislab/anndata/files/3216067/example_seurat.zip)

**Comment by ivirshup** [comment]
Sorry, I've been traveling for a bit and haven't had a chance to look too deeply at this yet. On my side, I'm able to read loom files from the HCA.

Could you send the code that generated that file? It'd be even more helpful if you could write the smallest example possible which generates a file that scanpy can't read.

**Comment by PedroRaposo** [comment]
Hi there @ivirshup, I have made a minimal computational generated Seurat object in R, then tried to import   it in Python using loompy and it seems fine. However using Anndata it gives the same error. I am going to send the script that I used, and the exported file, if it's useful. Thank you!

```
### In R

library(Matrix)
library(Seurat)
library(loomR)

# Constructing sparse matrix
x = c(1:10)
matrix = sparseMatrix(i = x, j = x, x = x)
rownames(matrix) = x
colnames(matrix) = x

# Constructing Seurat object and following its documented pipeline
seurat_object = CreateSeuratObject(counts = matrix)
seurat_object = NormalizeData(seurat_object, normalization.method = "LogNormalize", scale.factor = 10000)
seurat_object = FindVariableFeatures(seurat_object, selection.method = "vst", nfeatures = 2000)
all.genes = rownames(seurat_object)
seurat_object = ScaleData(seurat_object, features = all.genes)
seurat_object = RunPCA(seurat_object, features = VariableFeatures(object = seurat_object))

# Exporting object
as.loom(seurat_object, filename = "/path/to/seurat_object.loom")




### In Python

import scvelo as scv
import loompy

loom_file = loompy.connect("/home/AD/praposo/seurat_object.loom")
loom_file[:, :]

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  6.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]])


# Importing object
adata = scv.read("/path/to/seurat_object.loom", cache=True)

# Resultant error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/scanpy/readwrite.py", line 79, in read
    backup_url=backup_url, cache=cache, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/scanpy/readwrite.py", line 477, in _read
    adata = read_loom(filename=filename, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 186, in read_loom
    dtype=dtype)
  File "/opt/conda/lib/python3.7/site-packages/anndata/base.py", line 672, in __init__
    filename=filename, filemode=filemode)
  File "/opt/conda/lib/python3.7/site-packages/anndata/base.py", line 850, in _init_as_actual
    ['obs_names', 'row_names', 'smp_names'])
  File "/opt/conda/lib/python3.7/site-packages/anndata/base.py", line 287, in _gen_dataframe
    columns=[k for k in anno.keys() if k != index_name])
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 56, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 277, in _homogenize
    raise_cast_failure=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 658, in sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional
```

### Information that might be useful

# R Software versions
R - 3.5.1
Matrix library - 1.2.17
Seurat library - 3.0.0
loomR library - 0.2.1.9000

# Python Software versions
Python - 3.7.1
conda - 4.6.14
loompy - 2.0.16
anndata - 0.6.19
numpy - 1.16.3
pandas - 0.24.2
scanpy - 1.4.1
scikit-learn - 0.20.0
sklearn-pandas - 1.8.0
velocyto - 0.17.17

[seurat_object.zip](https://github.com/theislab/anndata/files/3247286/seurat_object.zip)

**Comment by ivirshup** [comment]
Great! That is exactly what I need.

While getting an environment setup was certainly painful (new R install), I can't reproduce this issue. The file that code creates reads in fine for me (I did only check reading with `anndata.read_loom`).

It looks like some of the python packages you used are a little out of date. Maybe updating those will help? Here's some version info from my end:

<details>
<summary> Python versions </summary>

```
scanpy==1.4.3 anndata==0.6.20 umap==0.3.9 numpy==1.16.4 scipy==1.3.0 pandas==0.24.2 
scikit-learn==0.21.2 statsmodels==0.9.0 loompy==2.0.17
```

</details>

<details>
<summary> R versions </summary>

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin18.5.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS/LAPACK: /usr/local/Cellar/openblas/0.3.6_1/lib/libopenblasp-r0.3.6.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_3.0.1     loomR_0.2.1.9000 hdf5r_1.2.0      R6_2.4.0        

loaded via a namespace (and not attached):
 [1] httr_1.4.0          tidyr_0.8.3         viridisLite_0.3.0  
 [4] jsonlite_1.6        bit64_0.9-7         splines_3.6.0      
 [7] lsei_1.2-0          R.utils_2.8.0       gtools_3.8.1       
[10] Rdpack_0.11-0       assertthat_0.2.1    ggrepel_0.8.1      
[13] globals_0.12.4      pillar_1.4.1        lattice_0.20-38    
[16] reticulate_1.12     glue_1.3.1          digest_0.6.19      
[19] RColorBrewer_1.1-2  SDMTools_1.1-221.1  colorspace_1.4-1   
[22] htmltools_0.3.6     cowplot_0.9.4       Matrix_1.2-17      
[25] R.oo_1.22.0         plyr_1.8.4          pkgconfig_2.0.2    
[28] bibtex_0.4.2        tsne_0.1-3          listenv_0.7.0      
[31] purrr_0.3.2         scales_1.0.0        RANN_2.6.1         
[34] gdata_2.18.0        Rtsne_0.15          tibble_2.1.2       
[37] ggplot2_3.1.1       ROCR_1.0-7          pbapply_1.4-0      
[40] lazyeval_0.2.2      survival_2.44-1.1   magrittr_1.5       
[43] crayon_1.3.4        R.methodsS3_1.7.1   future_1.13.0      
[46] nlme_3.1-139        MASS_7.3-51.4       gplots_3.0.1.1     
[49] ica_1.0-2           tools_3.6.0         fitdistrplus_1.0-14
[52] data.table_1.12.2   gbRd_0.4-11         stringr_1.4.0      
[55] plotly_4.9.0        munsell_0.5.0       cluster_2.0.8      
[58] irlba_2.3.3         compiler_3.6.0      rsvd_1.0.1         
[61] caTools_1.17.1.2    rlang_0.3.4         grid_3.6.0         
[64] ggridges_0.5.1      htmlwidgets_1.3     igraph_1.2.4.1     
[67] bitops_1.0-6        npsurv_0.4-0        gtable_0.3.0       
[70] codetools_0.2-16    reshape2_1.4.3      gridExtra_2.3      
[73] zoo_1.8-6           dplyr_0.8.1         future.apply_1.2.0 
[76] bit_1.1-14          KernSmooth_2.23-15  metap_1.1          
[79] ape_5.3             stringi_1.4.3       parallel_3.6.0     
[82] Rcpp_1.0.1          sctransform_0.2.0   png_0.1-7          
[85] tidyselect_0.2.5    lmtest_0.9-37    
```

</details>

**Comment by falexwolf** [comment]
```
  File "/opt/conda/lib/python3.7/site-packages/anndata/base.py", line 287, in _gen_dataframe
    columns=[k for k in anno.keys() if k != index_name])
```

It could be that in a previous version we didn't account for multi-dimensional `.col` and `.row` annotations in loom: the error hints to trying to initializing a column in `.obs` with something higher dimensional from loom (say, the PCs or `X_pca`). Evidently this is not possible and should instead go into `.obsm`. I'm not sure whether we do account for this now. But the fact that Isaac managed to run the code hints to it. 🙂

**Comment by falexwolf** [comment]
Yes, we're doing it these days: https://github.com/theislab/anndata/blob/a9390d6fca537fafdf9e93f1b85a91c10af7ca58/anndata/readwrite/read.py#L169 😄

**Comment by PedroRaposo** [comment]
@ivirshup, I updated the python modules exactly as you have, and it worked! Thank you very much!

@falexwolf Thank you for letting me know that!

**Comment by MichaelPeibo** [comment]
> Great! That is exactly what I need.
> 
> While getting an environment setup was certainly painful (new R install), I can't reproduce this issue. The file that code creates reads in fine for me (I did only check reading with `anndata.read_loom`). Additionally, I can read in the file you sent.
> 
> It looks like some of the python packages you used are a little out of date. Maybe updating those will help? Here's some version info from my end:
> 
>  Python versions
>  R versions

Updating all these packages works! Thanks! @ivirshup

**Comment by cakirb** [comment]
It works for me too!!

**Comment by brianhill11** [comment]
FWIW, I also tried updating the packages and still had an issue. Found that a few of my attributes had the shape (11990,1) but they needed to be (11990,). Removing the extra dimension with [:,0] fixed the issue.
