### ISSUE TITLE
'AxisArrays' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by czer1mj** [theislab/anndata#181]
Any time adata.obsm.dtype is accessed (only happens with non-Scanpy functions that I have notices), an error is thrown: **'AttributeError: 'AxisArrays' object has no attribute 'dtype''**

So far I can confirm that this occurs with BBKNN and UCSC-Cell-Browser when accessing an Anndata object created with anndata v0.6.22 and scanpy v1.4.2 (error from bbknn v1.3.3 and cellbrowser v0.5.35).

**BBKNN**
Traceback (most recent call last):
  File "mini_script.py", line 289, in <module>
    adata = bbknn.bbknn(adata, batch_key='sex', save_knn=True, copy=True)
  File "/home/mike/miniconda3/envs/scanpy/lib/python3.7/site-packages/bbknn/__init__.py", line 268, in bbknn
    if 'X_pca' not in adata.obsm.dtype.fields:
AttributeError: 'AxisArrays' object has no attribute 'dtype'

**UCSC Cell Browser**
Traceback (most recent call last):
  File "/home/mike/miniconda3/bin/cbImportScanpy", line 12, in <module>
    sys.exit(cbImportScanpyCli())
  File "/home/mike/miniconda3/lib/python3.7/site-packages/cellbrowser/convert.py", line 520, in cbImportScanpyCli
    markerField=markerField)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 3188, in scanpyToCellbrowser
    writeAnndataCoords(adata, layoutCode, path, layoutCode, layoutName, coordDescs)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 3000, in writeAnndataCoords
    existNames = anndata.obsm.dtype.names
AttributeError: 'AxisArrays' object has no attribute 'dtype'

**Comment by ivirshup** [comment]
Thanks for the error report!

The `.obsm` and `varm` used to be numpy arrays with structured datatypes. This was limiting for the kind of data that could be stored (no sparse matrices or dataframes), and made for inefficient updates. 

This caused an issue for people who were getting the keys of `obsm` and `varm` from the structured dtype of the array, instead of the `.keys()` method we'd added. The most recent version of `bbknn` has [this fixed](https://github.com/Teichlab/bbknn/pull/13), and I've open a PR for cellbrowser https://github.com/maximilianh/cellBrowser/pull/120.
