### ISSUE TITLE
transpose fails for backed='r'

### ISSUE THREAD

**Issue by bkmartinjr** [theislab/anndata#225]
Found while trying to support backed mode in cellxgene:  if I load an h5ad in backed mode, `.T` and `.transpose` fail:
* `adata.T` is simply missing
* `adata.transpose()` throws exception because `T` is missing
* and `adata.X.T` is missing (not sure it is guaranteed to exist, but it typically does with an ndarray or sparray).

Example:
```
>>> import anndata 
>>> ad = anndata.read_h5ad('example-dataset/pbmc3k.h5ad', backed='r')
>>> ad.T
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/core/anndata.py", line 1405, in transpose
    return AnnData(X.T, self._var, self._obs, self._uns,
AttributeError: 'Dataset' object has no attribute 'T'
>>> ad.transpose()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/core/anndata.py", line 1405, in transpose
    return AnnData(X.T, self._var, self._obs, self._uns,
AttributeError: 'Dataset' object has no attribute 'T'
>>> ad.X.T
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Dataset' object has no attribute 'T'
```

Version info:
```
anndata==0.6.22.post1
h5py==2.9.0
```

**Comment by ivirshup** [comment]
What were you expecting `adata.T` to do? I'm asking because I'm not completely sure what I'd expect it to do.

My first thought was it would require making a transposed copy of the entire object, and we currently require a path for that in backed mode. A transposed view of the backed object could work, but I'm not sure how much work that would take on our end.

**Comment by bkmartinjr** [comment]
Possibly naively, I was expecting a view.   Perhaps this is just a documentation bug, as the docs seem to indicate that these exist and work for all AnnData modes.  It would be very helpful if the docs made it clear which subset of the AnnData API work with all modes, and which are mode-specific.

**Comment by flying-sheep** [comment]
a view is a reasonable assumption and therefore possible feature!
