### ISSUE TITLE
Conceptual indexing problem

### ISSUE THREAD

**Issue by flying-sheep** [theislab/anndata#25]
The faster indexing solution

1. converts boolean indices to integer indices (we shouldn’t do that boolean indices are super fast!)
2. creates a pandas index using the `var_names` as index to speed up lookups

If the `var_names` happen to be strings, that works (slower than necessary), but if they’re integers, this breaks. Example:

```pytb
In[1]: ad = AnnData(np.array([[0,1,2],[3,4,5]]), var=dict(var_names=[10,11,12]))
In[2]: ad[:, ad.X.sum(0) > 3]
Traceback (most recent call last):
  File "<ipython-input-23-d08541977b75>", line 1, in <module>
    ad[:, ad.X.sum(0) > 3]
  File "anndata/base.py", line 1187, in __getitem__
    return self._getitem_view(index)
  File "anndata/base.py", line 1190, in _getitem_view
    oidx, vidx = self._normalize_indices(index)
  File "anndata/base.py", line 1167, in _normalize_indices
    var = _normalize_index(var, self.var_names)
  File "anndata/base.py", line 244, in _normalize_index
    positions = positions[index]
  File "pandas/core/series.py", line 809, in __getitem__
    return self._get_with(key)
  [...]
  File "pandas/core/indexing.py", line 1206, in _validate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)))
KeyError: 'None of [[1 2]] are in the [index]'
```

**Comment by falexwolf** [comment]
Great! :smile:
