### ISSUE TITLE
Reading tsv-files with only one column

### ISSUE THREAD

**Issue by Hoeze** [theislab/anndata#26]
Hi, I'd like to read a "barcode.tsv" file:
```
sc.read_csv("barcodes.tsv", delimiter="\t")
```
However, this file has only one column and cannot be loaded:
```
Traceback (most recent call last):
  File "<ipython-input-24-7055edd4368a>", line 13, in load_mtx_to_adata
    ad.obs = sc.read_csv("barcodes.tsv", delimiter="\t")
  File "/usr/lib/python3.6/site-packages/anndata/readwrite/read.py", line 36, in read_csv
    return read_text(filename, delimiter, first_column_names, dtype)
  File "/usr/lib/python3.6/site-packages/anndata/readwrite/read.py", line 210, in read_text
    return _read_text(f, delimiter, first_column_names, dtype)
  File "/usr/lib/python3.6/site-packages/anndata/readwrite/read.py", line 243, in _read_text
    .format(delimiter))
ValueError: Did not find delimiter "	" in first line.
```

**Comment by Hoeze** [comment]
Thanks for the help, now it's working
