### ISSUE TITLE
Slicing problems: observations not slicing .raw properly, and problems with specifying both dimensions

### ISSUE THREAD

**Issue by a-munoz-rojas** [theislab/anndata#264]
Hi all, 
I noticed two different problems with slicing recently. When I try to subset my data to include only certain observations, the raw attribute does not get sliced properly. Interestingly, the matrix held in adata.raw.X is sliced properly, but not the obs_names or n_obs. This creates some issue when trying to slice for a second time.
Below is a reproducible example:

```pytb
import scanpy as sc
import numpy as np
adata = sc.datasets.blobs()
adata.raw = adata
slice = np.isin(adata.obs['blobs'], ['2', '3', '4'])
adata = adata[slice].copy()
print(adata.n_obs)
Out: 384
print(adata.raw.n_obs)
Out: 640
print(np.any(adata.X != adata.raw.X))
Out: False
```

Now if I try to subset the data and get the raw matrix again, it fails because of this difference:
```pytb
adata.raw[adata.obs['blobs'] == '2']
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 335, in __getitem__
    oidx, vidx = self._normalize_indices(index)
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 363, in _normalize_indices
    obs = _normalize_index(obs, self._adata.obs_names)
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 160, in _normalize_index
    positions = positions[index]
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/pandas/core/series.py", line 1111, in __getitem__
    key = check_bool_indexer(self.index, key)
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/pandas/core/indexing.py", line 2424, in check_bool_indexer
    "Item wrong length {} instead of {}.".format(len(result), len(index))
IndexError: Item wrong length 384 instead of 640.
```

This might be related to another bug with slicing - if you specify both dimensions, it seems to break the slicing (e.g. adata[slice, :] vs adata[slice]). This only seems to be a problem if you set the .raw property first, otherwise it doesn't matter. Below is another example:

```pytb
adata = sc.datasets.blobs()
adata.raw = adata
slice = np.isin(adata.obs['blobs'], ['2', '3', '4'])
adata = adata[slice].copy()
adata = adata[adata.obs['blobs'] == '2', :]
Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 1230, in __getitem__
    return self._getitem_view(index)
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 1234, in _getitem_view
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 561, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 633, in _init_as_view
    self._raw = adata_ref.raw[oidx]
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 335, in __getitem__
    oidx, vidx = self._normalize_indices(index)
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 363, in _normalize_indices
    obs = _normalize_index(obs, self._adata.obs_names)
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/anndata/core/anndata.py", line 160, in _normalize_index
    positions = positions[index]
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/pandas/core/series.py", line 1111, in __getitem__
    key = check_bool_indexer(self.index, key)
  File "/Users/andres/miniconda3/envs/testnew/lib/python3.7/site-packages/pandas/core/indexing.py", line 2424, in check_bool_indexer
    "Item wrong length {} instead of {}.".format(len(result), len(index))
IndexError: Item wrong length 384 instead of 640.
```
There seems to be no problem if you don't specificy the second dimension:
```pytb
adata = adata[adata.obs['blobs'] == '2']
```
Don't know if these bugs are related but since they both depend on setting the .raw variable first, I thought they might be.

**Comment by ivirshup** [comment]
Thanks for the bug report! I don't get any of these errors on master, so I think this has been fixed there.

**Comment by a-munoz-rojas** [comment]
Thanks for your reply @ivirshup. You're right, I checked with an installation from master and it's been fixed. I was previously using the version from conda (1.4.4.post1). Thanks anyways!
