### ISSUE TITLE
Failure to load loom file / dependency list

### ISSUE THREAD

**Issue by cap76** [theislab/anndata#356]
Hi, I'm trying to run scvelo but falling at almost the first hurdle. I have a loom file from a 10X dataset. When I try to load in the data:

adata = scv.read(filename, cache=True)

I get the error below. I suspected maybe I'm missing a dependency or outdated version of a dependency. Is there a full list of package versions required? 

Traceback (most recent call last):
  File "/Users/christopherpenfold/Desktop/Aracely/scVelo/env/lib/python3.6/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/Users/christopherpenfold/Desktop/Aracely/scVelo/env/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 463, in read_dataframe
    columns = list(group.attrs["column-order"])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/christopherpenfold/Desktop/Aracely/scVelo/env/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'column-order')"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/christopherpenfold/Desktop/Aracely/scVelo/env/lib/python3.6/site-packages/scanpy/readwrite.py", line 122, in read
    **kwargs,
  File "/Users/christopherpenfold/Desktop/Aracely/scVelo/env/lib/python3.6/site-packages/scanpy/readwrite.py", line 661, in _read
    return read_h5ad(path_cache)
  File "/Users/christopherpenfold/Desktop/Aracely/scVelo/env/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 411, in read_h5ad
    d[k] = read_dataframe(f[k])
  File "/Users/christopherpenfold/Desktop/Aracely/scVelo/env/lib/python3.6/site-packages/anndata/_io/utils.py", line 163, in func_wrapper
    f"Above error raised while reading key {elem.name!r} of "
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/var' of type <class 'h5py._hl.group.Group'> from /.

**Comment by ivirshup** [comment]
Could you try the `read_loom` function?

**Comment by cap76** [comment]
Okay problem solved. I managed to get things working with virtual env. The main issue was the loom file was a pre merged loom fle, loaded in separately and concatenate.

Thanks for getting back to me, can close the threat :-)
