### ISSUE TITLE
Concatenation errors with numpy<1.15

### ISSUE THREAD

**Issue by juhaa** [theislab/anndata#385]
Hi,

During concatenation of two anndata objects together this error occurred:
```
>>> adata = HCA.concatenate(Ute, batch_categories=['HCA', 'Ute'])
/work/juha/miniconda3/envs/pyscenic_new/lib/python3.6/site-packages/anndata/_core/merge.py:461: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  obs = pd.concat([a.obs for a in adatas], ignore_index=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/juha/miniconda3/envs/pyscenic_new/lib/python3.6/site-packages/anndata/_core/anndata.py", line 1717, in concatenate
    .argsort(kind="stable")
  File "/work/juha/miniconda3/envs/pyscenic_new/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4688, in argsort
    return result.argsort(*args, **kwargs)
ValueError: stable is an unrecognized kind of sort

```
Quickly checking seems like the pandas argsort doesn't have the option "stable", but numpy's argsort does (added in ver 1.15.0, anndata requires numpy~=1.14).

Versions:
```
anndata                   0.7.3                    pypi_0    pypi
numpy                     1.14.6           py36h3b04361_4
pandas                    0.25.3           py36he6710b0_0
```

The anndata objects were originally created with versions
```
anndata                   0.7.2.dev85+gb6be1d2          pypi_0    pypi
```
and
```
anndata                   0.6.19                   pypi_0    pypi
```

BR,
Juha

**Comment by ivirshup** [comment]
Hi! To me, this looks like a problem with conflicting version of numpy and pandas. Could you try upgrading those and seeing if that works?

**Comment by juhaa** [comment]
Hi,

Updating the packages worked. Tested separately updating either pandas or numpy and indeed seems like numpy version >=1.15 is required.
