### ISSUE TITLE
np.str_ Dataframe column names error on write

### ISSUE THREAD

**Issue by scottgigante** [theislab/anndata#456]
I'm hitting this error despite my AnnData object apparently having no Unicode data attached to it.

[adata.zip](https://github.com/theislab/anndata/files/5556814/adata.zip)

```{python}
import pickle
with open("adata.pickle", "rb") as f:
    adata = pickle.load(f)

adata.write_h5ad("adata.h5ad")
```

```{pytb}
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/anndata/_io/utils.py", line 188, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 258, in write_dataframe
    group.attrs["column-order"] = list(df.columns)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 103, in __setitem__
    self.create(name, data=value)
  File "/usr/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 180, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1629, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1653, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1719, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U12')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1844, in write_h5ad
    _write_h5ad(
  File "/usr/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 118, in write_h5ad
    write_attribute(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 139, in write_attribute_h5ad
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/anndata/_io/utils.py", line 191, in func_wrapper
    raise type(e)(
TypeError: No conversion path for dtype: dtype('<U12')

Above error raised while writing key 'obs' of <class 'h5py._hl.files.File'> from /.
```

Versions: 

<details>

```
sc.logging.print_versions()
WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.5
scanpy      1.6.0
sinfo       0.3.1
-----
PIL                 7.2.0
PyQt5               NA
anndata             0.7.5
appdirs             1.4.4
cffi                1.14.3
colorama            0.4.4
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
get_version         2.1
google              NA
h5py                3.0.0
igraph              0.8.3
joblib              0.16.0
kiwisolver          1.3.1
legacy_api_wrap     1.2
llvmlite            0.34.0
louvain             0.7.0
matplotlib          3.3.2
mpl_toolkits        NA
natsort             7.0.1
numba               0.51.2
numexpr             2.7.1
numpy               1.18.3
packaging           20.4
pandas              1.1.3
pkg_resources       NA
psutil              5.7.2
pyparsing           2.4.7
pytoml              NA
pytz                2020.4
scanpy              1.6.0
scipy               1.5.2
setuptools_scm      NA
sinfo               0.3.1
sip                 NA
six                 1.15.0
sklearn             0.23.2
tables              3.6.1
texttable           1.6.3
typing_extensions   NA
wcwidth             0.2.5
yaml                5.3.1
-----
Python 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
Linux-5.9.6-arch1-1-x86_64-with-glibc2.2.5
64 logical CPU cores
-----
Session information updated at 2020-11-17 18:37
```

</details>

**Comment by ivirshup** [comment]
It looks like the column name of your `obs` somehow is a numpy unicode string:

```python
In [13]: type(adata.obs.columns[0])
Out[13]: numpy.str_
```

It looks like we should be casting column names to python strings.

**Comment by scottgigante** [comment]
Good catch, thank you!

**Comment by ivirshup** [comment]
No problem.

While they print the same, numpy string and numbers aren't handled by a lot of libraries (e.g. `json.dumps({"a": np.int64(1)})` errors). It's caught me enough that now it's always one of my first suspicions.
