### ISSUE TITLE
Error concatenating anndata objects for scvelo analysis

### ISSUE THREAD

**Issue by GabrielBaldissera** [theislab/anndata#520]
Hi, guys.

I am following this tutorial to integrate my loom data with my seurat metadata for a subset of cells. My current issue is that I have two anndata objects from two different loom files that I would like to concatanate but I'm getting an error.

Given that the loom files don't have any sample sufix in the barcodes but Seurat does, I have added a new observation named "Barcodes" which includes the sufixes so that I can match the loom objects to my Seurat data and then filter them to have the same cells as in seurat.

Here is the code for that:

#Load loom files
sample_JG12_WT = anndata.read_loom("JG12__WT.loom") 
sample_JG13_MT = anndata.read_loom("JG13__MT.loom")

#Clean cell names to keep only barcode
scv.utils.clean_obs_names(sample_JG12_WT)
scv.utils.clean_obs_names(sample_JG13_MT)

#Add Sample prefix to barcodes in the objects
sample_JG13_MT.obs["Barcodes"] =[str("MT_")+str(gene)+str(-1) for gene in sample_JG13_MT.obs_names] 
sample_JG12_WT.obs["Barcodes"] =[str("WT_")+str(gene)+str(-1) for gene in sample_JG12_WT.obs_names] 

##Filter loom based on subset of cells
#Get barcodes observed for based on sample pattern
cellID_obs_sample_MT = sample_obs[sample_obs["Cells(mi128_data_R1)"].str.contains("MT_")] 
cellID_obs_sample_WT = sample_obs[sample_obs["Cells(mi128_data_R1)"].str.contains("WT_")] 
#Filter loom based on the matching barcodes
sample_JG13_MT = sample_JG13_MT[np.isin(sample_JG13_MT.obs["Barcodes"], cellID_obs_sample_MT)] 
sample_JG12_WT = sample_JG12_WT[np.isin(sample_JG12_WT.obs["Barcodes"], cellID_obs_sample_WT)] 

#Concatenate filtered samples
concatanated_samples = sample_JG12_WT.concatenate(sample_JG13_MT) 

    sample_JG12_WT.concatenate(sample_JG13_MT)

    Traceback (most recent call last):
    File "/home/ba/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    File "", line 1, in
    sample_JG12_WT.concatenate(sample_JG13_MT)
    File "/home/ba/.local/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1696, in concatenate
    out = concat(
    File "/home/ba/.local/lib/python3.8/site-packages/anndata/_core/merge.py", line 814, in concat
    alt_annot = merge_dataframes(
    File "/home/ba/.local/lib/python3.8/site-packages/anndata/_core/merge.py", line 526, in merge_dataframes
    dfs = [df.reindex(index=new_index) for df in dfs]
    File "/home/ba/.local/lib/python3.8/site-packages/anndata/_core/merge.py", line 526, in
    dfs = [df.reindex(index=new_index) for df in dfs]
    File "/home/ba/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 312, in wrapper
    return func(*args, **kwargs)
    File "/home/ba/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4176, in reindex
    return super().reindex(**kwargs)
    File "/home/ba/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4811, in reindex
    return self._reindex_axes(
    File "/home/ba/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4022, in _reindex_axes
    frame = frame._reindex_index(
    File "/home/ba/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4041, in _reindex_index
    return self._reindex_with_indexers(
    File "/home/ba/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4877, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
    File "/home/ba/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1301, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
    File "/home/ba/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3476, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
    ValueError: cannot reindex from a duplicate axis

This is what I have inside each filtered object right now:

sample_JG13_MT

    Out[142]:
    View of AnnData object with n_obs × n_vars = 2733 × 36351
    obs: 'Barcodes'
    var: 'Accession', 'Chromosome', 'End', 'Start', 'Strand'
    layers: 'matrix', 'ambiguous', 'spliced', 'unspliced'

sample_JG12_WT

    Out[143]:
    View of AnnData object with n_obs × n_vars = 3438 × 36351
    obs: 'Barcodes'
    var: 'Accession', 'Chromosome', 'End', 'Start', 'Strand'
    layers: 'matrix', 'ambiguous', 'spliced', 'unspliced'

Does any of you has any suggestion on how to merge the two anndata object? I would like to have a unique anndata object where I could match the cell barcodes and add my embbedings and cluster information for the RNA velocity analysis.
Thank you very much for your help!

Best,
Gabriel

**Comment by AAA-3** [comment]
How did you go about solving this?

**Comment by PeifengJi** [comment]
Hi AAA-3
    I have encountered the same issue. I resolved the problem by using the .var_names_make_unique() and obs_names_make_unique() commands. 
   Hope this helps!

**Comment by PeifengJi** [comment]
> How did you go about solving this?

Hi AAA-3
I have encountered the same issue. I resolved the problem by using the .var_names_make_unique() and obs_names_make_unique() commands.
Hope this helps!
