### ISSUE TITLE
Error in reading endocrinogenesis_day15.h5ad

### ISSUE THREAD

**Issue by jfouyang** [theislab/anndata#563]
Hi, I have previously downloaded the file `endocrinogenesis_day15.h5ad` which is used for the scvelo package tutorial.

The file can be downloaded from [here](http://files.ddnetbio.com/shinyCell/endocrinogenesis_day15.h5ad)

After updating to the latest version of anndata, I can no longer open the file. I ran the following code and got the error below:
```
>>> tmp = ad.read_h5ad("endocrinogenesis_day15.h5ad")
Traceback (most recent call last):
  File "/home/john/miniconda3/lib/python3.8/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/home/john/miniconda3/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 469, in read_dataframe_legacy
    _decode_structured_array(
  File "/home/john/miniconda3/lib/python3.8/site-packages/anndata/compat/__init__.py", line 112, in _decode_structured_array
    decode(arr[k], out=arr[k])
  File "/home/john/miniconda3/lib/python3.8/site-packages/anndata/compat/__init__.py", line 108, in <lambda>
    decode = np.frompyfunc(lambda x: x.decode("utf-8"), 1, 1)
AttributeError: 'str' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/john/miniconda3/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 424, in read_h5ad
    d[k] = read_dataframe(f[k])
  File "/home/john/miniconda3/lib/python3.8/site-packages/anndata/_io/utils.py", line 159, in func_wrapper
    raise e
  File "/home/john/miniconda3/lib/python3.8/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/home/john/miniconda3/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 482, in read_dataframe
    return read_dataframe_legacy(group)
  File "/home/john/miniconda3/lib/python3.8/site-packages/anndata/_io/utils.py", line 162, in func_wrapper
    raise AnnDataReadError(
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/obs' of type <class 'h5py._hl.dataset.Dataset'> from /.
```

Can you help?

**Comment by ivirshup** [comment]
I'm able to read that with the anndata 0.7.6 release. My suspicion is that this has to do with `h5py` versions. Here's what I have installed:

<details>
<summary> Versions I tested with </summary>

```python
from sinfo import sinfo
sinfo(dependencies=True)
```

```python

-----
anndata     0.7.6
sinfo       0.3.1
-----
anndata             0.7.6
appnope             0.1.0
asciitree           NA
backcall            0.2.0
cloudpickle         1.6.0
colorama            0.4.4
cython_runtime      NA
dask                2021.04.1
dateutil            2.8.1
decorator           4.4.2
fasteners           NA
fsspec              0.8.7
google              NA
h5py                3.2.1
ipykernel           5.5.4
ipython_genutils    0.2.0
jedi                0.17.2
llvmlite            0.36.0
monotonic           NA
mpl_toolkits        NA
msgpack             1.0.0
natsort             7.1.1
numba               0.53.1
numcodecs           0.7.3
numpy               1.20.2
packaging           20.9
pandas              1.2.4
parso               0.7.1
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prompt_toolkit      3.0.18
psutil              5.8.0
ptyprocess          0.6.0
pygments            2.7.0
pytz                2020.1
scipy               1.6.3
sinfo               0.3.1
sitecustomize       NA
six                 1.15.0
snappy              NA
sparse              0.12.0+21.gc96cc1a
sphinxcontrib       NA
storemagic          NA
tblib               1.6.0
tlz                 0.11.1
toolz               0.11.1
tornado             6.1
traitlets           5.0.5
typing_extensions   NA
wcwidth             0.2.5
yaml                5.3.1
zappy               NA
zarr                2.8.1
zmq                 19.0.2
-----
IPython             7.23.1
jupyter_client      6.1.11
jupyter_core        4.7.0
jupyterlab          2.2.9
notebook            6.3.0
-----

```

</details>

Could you share the package versions you have installed?

**Comment by jfouyang** [comment]
It seems like it's a problem with an older version of anndata. Using your code, I checked that I was using anndata v0.7.5 previously. The error went away after updating to v0.7.6. For completeness, I have included the version information for both cases. Thanks so much for the help!

On a side note: Hi Issac, I am a postdoc from Owen Rackham's lab at Duke-NUS.  I think we met very briefly once during a single-cell conference at Tokyo, Odaiba two years back~ Thanks so much for the help and hope to see you in person soon!

```
### Version where it is NOT working
>>> sinfo(dependencies=True)
-----
anndata     0.7.5
sinfo       0.3.1
-----
anndata             0.7.5
cloudpickle         1.6.0
cython_runtime      NA
cytoolz             0.11.0
dask                2021.05.0
dateutil            2.8.1
fsspec              2021.05.0
google              NA
h5py                2.10.0
mpl_toolkits        NA
natsort             7.1.1
numpy               1.20.2
packaging           20.9
pandas              1.2.4
psutil              5.8.0
pytz                2021.1
scipy               1.6.3
sinfo               0.3.1
six                 1.16.0
tblib               1.7.0
tlz                 0.11.0
toolz               0.11.1
typing_extensions   NA
yaml                5.4.1
-----

### Version where it is working
>>> sinfo(dependencies=True)
-----
anndata     0.7.6
sinfo       0.3.1
-----
anndata             0.7.6
cloudpickle         1.6.0
cython_runtime      NA
cytoolz             0.11.0
dask                2021.05.0
dateutil            2.8.1
fsspec              2021.05.0
google              NA
h5py                2.10.0
mpl_toolkits        NA
natsort             7.1.1
numpy               1.20.2
packaging           20.9
pandas              1.2.4
psutil              5.8.0
pytz                2021.1
scipy               1.6.3
sinfo               0.3.1
six                 1.16.0
tblib               1.7.0
tlz                 0.11.0
toolz               0.11.1
typing_extensions   NA
yaml                5.4.1
-----
```

**Comment by ivirshup** [comment]
> On a side note

Hey! Ah yes, back when we could meet people at in-person conferences 😢. Well, Singapore is definitely at the top of my list once we can travel again!

No worries about the help, and hope the cases over there clear up soon! A bit worried Melbourne is headed to a similar situation at the moment.

**Comment by bclopesrs** [comment]
I've been running into the same issues when I try to run it in R (endocrinogenesis_day15.h5ad). I tried to update the anndata package, but I couldn't. May someone help me?




Error in py_call_impl(callable, dots$args, dots$keywords) : 
  OSError: Unable to open file (file signature not found)

Detailed traceback:
  File "C:\Users\bclop\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\anndata\_io\h5ad.py", line 224, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "C:\Users\bclop\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\h5py\_hl\files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\bclop\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\h5py\_hl\files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
