### ISSUE TITLE
Accessing `"distances"` from `adata.uns["neighbors"]` fails

### ISSUE THREAD

**Issue by WeilerP** [theislab/anndata#617]
## Description

The following code breaks when trying to access `adata.uns["neighbors"]["distances"]`:

```python
import numpy as np
from anndata import AnnData

adata = AnnData(np.eye(2), uns={"neighbors": {"distances": 2}})
adata.uns["neighbors"]["distances"]
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/anndata/lib/python3.8/site-packages/anndata/compat/_overloaded_dict.py", line 98, in __getitem__
    return self.overloaded[key].get()
  File "/miniconda3/envs/anndata/lib/python3.8/site-packages/anndata/compat/_overloaded_dict.py", line 160, in _adjacency_getter
    return adata.obsp[key]
  File "/miniconda3/envs/anndata/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py", line 148, in __getitem__
    return self._data[key]
KeyError: 'distances'
```

I suppose the problem is that `"distances"` is in a sense a reserved key which will be moved from `adata.uns["neighbors"]` to `adata.obsp` automatically if dimensions match, e.g.

```python
import numpy as np
from anndata import AnnData

adata = AnnData(np.eye(2), uns={"neighbors": {"distances": np.eye(2)}})
```

results in

```
AnnData object with n_obs × n_vars = 2 × 2
    uns: 'neighbors'
    obsp: 'distances'
```

Calling `adata.uns["neighbors"]["distances"]` seems to be rerouted to `adata.obsp["distances"]` no matter what.

## Versions

> anndata==0.7.6

**Comment by WeilerP** [comment]
I'm aware that this is an edge case and will most likely never cause an issue IRL but the error should be handled more graciously or, even better, not be raised at all, IMO. Any thoughts, @ivirshup?

**Comment by flying-sheep** [comment]
this has been fixed, I think by removing the old compat code
