### ISSUE TITLE
Writing + reading again not working

### ISSUE THREAD

**Issue by Hoeze** [theislab/anndata#84]
```python
# adata.obs_names
Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            4937, 4938, 4939, 4940, 4941, 4942, 4943, 4944, 4945, 4946],
           dtype='int64', length=20728)

# adata.obs.head()
                col_0 batch condition         source
0  AAACCTGAGACGACGT-1     1        S4  170804_X_S4_1
1  AAACCTGAGAGGGATA-1     1        S4  170804_X_S4_1
2  AAACCTGCACGTAAGG-1     1        S4  170804_X_S4_1
3  AAACCTGCAGTAAGCG-1     1        S4  170804_X_S4_1
4  AAACCTGCAGTCAGCC-1     1        S4  170804_X_S4_1

# adata.obs.dtypes
col_0        category
batch        category
condition    category
source       category
dtype: object
```
writing and reading again:
```python
# adata.write("sample_data.h5ad")
 storing 'col_0' as categorical
 storing 'condition' as categorical
 storing 'source' as categorical
 storing 'col_1' as categorical
# adata2 = ad.read_h5ad("sample_data.h5ad")
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/pandas/core/arrays/categorical.py", line 581, in from_codes
    codes = coerce_indexer_dtype(np.asarray(codes), categories)
  File "/opt/miniconda3/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 606, in coerce_indexer_dtype
    return _ensure_int16(indexer)
  File "pandas/_libs/algos_common_helper.pxi", line 3209, in pandas._libs.algos.ensure_int16
  File "pandas/_libs/algos_common_helper.pxi", line 3214, in pandas._libs.algos.ensure_int16
ValueError: invalid literal for int() with base 10: 'ENSG00000243485'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-98ad2411787c>", line 1, in <module>
    adata2 = ad.read_h5ad("/home/hoelzlwimmerf/Masterarbeit/data/sample_data.h5ad")
  File "/opt/miniconda3/lib/python3.6/site-packages/anndata/readwrite/read.py", line 426, in read_h5ad
    return AnnData(d)
  File "/opt/miniconda3/lib/python3.6/site-packages/anndata/base.py", line 671, in __init__
    filename=filename, filemode=filemode)
  File "/opt/miniconda3/lib/python3.6/site-packages/anndata/base.py", line 794, in _init_as_actual
    X, obs, var, uns, obsm, varm, raw, layers = self._from_dict(X)
  File "/opt/miniconda3/lib/python3.6/site-packages/anndata/base.py", line 2090, in _from_dict
    categories=v)
  File "/opt/miniconda3/lib/python3.6/site-packages/pandas/core/arrays/categorical.py", line 584, in from_codes
    "codes need to be convertible to an arrays of integers")
ValueError: codes need to be convertible to an arrays of integers
```
When debugging the position where it throws the error:
```python
# d_true_keys['var'][k_stripped].values
array(['ENSG00000243485', 'ENSG00000237613', 'ENSG00000186092', ...,
       'ENSG00000251180', 'ENSG00000215616', 'ENSG00000215611'],
      dtype=object)
# v
array(['AAACCTGAGAACTCGG-1', 'AAACCTGAGAAGATTC-1', 'AAACCTGAGACGACGT-1',
       ..., 'TTTGTCATCGTTACGA-1', 'TTTGTCATCTCCAGGG-1',
       'TTTGTCATCTTAACCT-1'], dtype='<U18')
# k_stripped
'col_0'
```

**Comment by Hoeze** [comment]
AnnData version is 0.6.13

**Comment by falexwolf** [comment]
Hm, never saw this before. 

Is it trying to make a categorical out of the gene ids?
```
ValueError: invalid literal for int() with base 10: 'ENSG00000243485'
```

But I cannot debug it given this information... I'd need a file...

**Comment by ivirshup** [comment]
It looks like the error here is from `obs_names` being integers, which is unsupported.
